scll: client.o singly_circular_linked_list.o
	ld -dynamic-linker /lib/ld-linux.so.2 -lc -o scll $^ -e main

client.o: client.S
	as -o client.o client.S

singly_circular_linked_list.o: singly_circular_linked_list.S
	as -o singly_circular_linked_list.o singly_circular_linked_list.S

clean:
	rm scll
